# Generated by Django 6.0.4 on 2026-04-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrescriptionItems',
            new_name='PrescriptionItem',
        ),
    ]
