# Generated by Django 4.2.30 on 2026-04-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_rename_prescriptionitems_prescriptionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecord',
            name='is_test_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
