# Generated by Django 4.2.30 on 2026-04-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_test_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
