# Generated by Django 4.2.30 on 2026-04-21 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
