# Generated by Django 4.2.30 on 2026-04-21 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_doctor_alter_appointment_patient'),
        ('accounts', '0001_initial'),
        ('scheduling', '0002_doctorschedule_slot_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='buffer_time_minutes',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.doctorprofile'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['doctor', 'day_of_week'], name='scheduling__doctor__154e7c_idx'),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='accounts.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='scheduling.doctorschedule'),
        ),
        migrations.AddIndex(
            model_name='doctorslot',
            index=models.Index(fields=['doctor', 'status', 'start_time'], name='scheduling__doctor__522336_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorslot',
            index=models.Index(fields=['start_time'], name='scheduling__start_t_b1bcfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorslot',
            constraint=models.UniqueConstraint(fields=('doctor', 'start_time'), name='unique_doctor_slot_start_time'),
        ),
    ]
