# Generated by Django 4.2.30 on 2026-04-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_doctorslot_doctorschedule_buffer_time_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doctorslot',
            name='scheduling__doctor__522336_idx',
        ),
        migrations.RemoveField(
            model_name='doctorslot',
            name='status',
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='doctorslot',
            index=models.Index(fields=['doctor', 'is_available', 'start_time'], name='scheduling__doctor__f51d76_idx'),
        ),
    ]
