# Generated by Django 4.2.30 on 2026-04-21 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_remove_doctorslot_scheduling__doctor__522336_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='buffer_time_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
