# Generated by Django 4.2.30 on 2026-04-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_doctorschedule_buffer_time_minutes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorSlot',
        ),
    ]
