# Generated by Django 4.2.30 on 2026-04-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scheduling', '0005_alter_doctorschedule_buffer_time_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_date', models.DateField()),
                ('exception_type', models.CharField(choices=[('off', 'Day Off/Vacation'), ('work', 'One-off Working Day')], max_length=50)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('slot_duration_minutes', models.IntegerField(default=30)),
                ('buffer_time_minutes', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='accounts.doctorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='scheduling.scheduleexception'),
        ),
    ]
