# Generated by Django 4.2.30 on 2026-04-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_scheduleexception_doctorslot_exception'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scheduleexception',
            constraint=models.UniqueConstraint(fields=('doctor', 'exception_date'), name='unique_doctor_exception_date'),
        ),
    ]
