# Generated by Django 4.2.30 on 2026-04-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_scheduleexception'),
    ]

    operations = []
